# Import all necessary
from random import randint

# Variable Creation
min = 1
max = 10
low = 1
high = 10
yes = ["yes", "y", "yep", "affirmative"]
no = ["no", "n", "nope", "negative"]


# Function Definitions
def clear(variable):
    variable = None

def instructions():
    input("Okay, Here are the instructions:")
    input(" -A token will be randomly generated by this program- ")
    input(" -It can be one of 4 types: Zebra, Horse, Donkey or Unicorn- ")
    input(" -If it is a Zebra or Donkey, you will win 50c,\n and if it is a Unicorn, you will win $5- ")
    input(" -Unfortunately, if it is a donkey, you will go home empty handed- ")

def yes_no(question):
    yes_no.answer = None
    clear(yes_no.answer)
    while True:
        yes_no.answer = input(question).lower().strip()
        if yes_no.answer in yes:
            yes_no.answer = True
            break

        elif yes_no.answer in no:
            yes_no.answer = False
            break

        else:
            print("Please answer with a yes or no")

def num_check(question, low, high):
    error = "Please give a whole number between {} and {} as your response\n".format(low, high)

    valid = False
    while not valid:
        try:
            # Ask question and get response
            response = int(input(question))

            # Check to see whether the response is expected
            if low <= response <= high:
                print("Game Continues")
                return response

            else:
                print(error)
        # If unexpected value, re-run question
        except ValueError:
            print(error)

def num_gen():
    for _ in range(1):
        value = int(randint(min, max))
        if 0 < value <= 25:
            num_gen.token = "Zebra"
            statement = "Not bad, could be worse\n"
            num_gen.value = 0.5

        elif 25 < value <= 50:
            num_gen.token = "Horse"
            statement = "Not bad, could be worse\n"
            num_gen.value = 0.5

        elif 50 < value <= 90:
            num_gen.token = "😢😢 Donkey 😢😢"
            statement = "Unlucky, hopefully you do better next time\n"
            num_gen.value = 0

        elif 90 < value <= 100:
            num_gen.token = "🦄🦄 Unicorn 🦄🦄"
            statement = "Wow, that's fantastic, you really won big!\n"
            num_gen.value = 5

    print("Generating token...")
    print("You got a {}".format(num_gen.token))
    print(statement)


# Main Routine
print("""
-----------------------------------
  🦄 Welcome to Lucky Unicorns 🦄
-----------------------------------""")
yes_no("Have you played the lucky unicorn game before?\n")
if yes_no.answer is True:
    print("Ok then, let's go!")
elif yes_no.answer is False:
    instructions()
    print("Ok then, let's go!")
num_check("How much do you want to add to your balance ($1 = 1 round)\n ", low, high)
