#Import all necessary
import random

#Create Variables
yes = ["yes", "y", "yep", "affirmative"]
no = ["no", "n", "nope", "negative"]
low = 1
high = 10
instruction = False

#Define functions
def instructions():
    input("Okay, Here are the instructions:")
    input(" -A token will be randomly generated by this program- ")
    input(" -It can be one of 4 types: Zebra, Horse, Donkey or Unicorn- ")
    input(" -If it is a Zebra or Donkey, you will win 50c,\n and if it is a Unicorn, you will win $5- ")
    input(" -Unfortunately, if it is a donkey, you will go home empty handed- ")

def yes_no(question):
    valid = False
    while not valid:
    # Ask question
        answer = input(question).lower().strip()
    # If yes, continue program
        if answer in list(yes):
            valid = True
            return answer
            return response
        elif answer in list(no) and instruction == True:
            num_check("How many rounds do you want to play? ", low, high)

        elif answer in list(no):
            instructions()
            valid = True
        # If anything else
        else:
            print("Please answer with a yes or no answer")

def num_check(question, low, high):
    error = "Please give a whole number between {} and {} as your response\n".format(low, high)

    valid = False
    while not valid:
        try:
            #Ask question and get response
            response = int(input(question))

            #Check to see whether the response is expected
            if low <= response <= high:
                yes_no("Ok, so you want {} round/s?\n".format(response))
                return response

            else:
                print(error)
        #If unexpected value, re-run question
        except ValueError:
            print(error)

#Main body
print("""
-----------------------------------
  🦄 Welcome to Lucky Unicorns 🦄
-----------------------------------""")
yes_no("Have you played the lucky unicorn game before?\n ")
input("Okay then, we're ready to start!\n")
instruction = True
num_check("How many rounds do you want to play?\n ", low, high)

